# Generated by Django 5.1.1 on 2024-09-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("url", models.TextField()),
                ("count", models.IntegerField(default=1)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["method", "url"], name="users_log_method_c323db_idx"
                    )
                ],
            },
        ),
    ]
